### ISSUE TITLE
Automatic podcast segment Post generation and meta linking

### ISSUE THREAD

**Issue by rveitch** [openfcci/fcc-northland-outdoors-radio#5]
- [x] Add hook/function triggered when published a new podcast that automatically generates three new standard posts (one for each segment)
  - [x] New post status is pre-set to "draft"
  - [x] Auto-populate the post title from the corresponding post segment
  - [x] Auto-populate the post content from the corresponding post description
  - [x] Add post meta with the post_id of the corresponding podcast episode
  - [x] Conditionals: If the post url/id meta are already present for a segment, do not create a new post, instead update the corresponding post info

### Video Embedding
- [x] Auto-populate the embed script into the post meta:
  - Meta Key: `mvp_video_embed`
  - Example script: `<script type="text/javascript" src="http://content.jwplatform.com/players/5zNMKp1e-XmRneLwC.js"></script>`

```php
$mvp_video_embed = '<script type="text/javascript" src="http://content.jwplatform.com/players/' . $segment_1_jw_key .'-XmRneLwC.js"></script>'
update_post_meta($post->ID, 'mvp_video_embed', $mvp_video_embed );
```

***

**Needs Further Consideration**
- Add post meta with the jw player key of the corresponding podcast episode
  - Add RSB ACF read-only message or text display field
- Pre-populate & prefix the post content with the jw player shortcode/key, -OR- 
- Automatically prepend the post content with the jw player shortcode/key (Better solution?)
- Shortcode function for returning segment info
- Shortcode function for returning full week podcast info (& upcoming shows?)

### Reference
- https://developer.wordpress.org/reference/functions/wp_insert_post/

**Comment by jgrinsteinner** [comment]
@rveitch Reminder that this code needs to be reviewed
